Add sanity check that output dir must be specified for multi module maven builds

diff --git a/java/s2i/assemble b/java/s2i/assemble
--- a/java/s2i/assemble
+++ b/java/s2i/assemble
@@ -8,8 +8,6 @@ fi
 # Which version of hawt app to use
 hawt_app_version="2.2.53"
 
-# ==============================================================================
-
 # Global S2I variable setup
 source `dirname "$0"`/s2i-setup
 
@@ -29,6 +27,15 @@ function check_error() {
 }
 
 function get_output_dir() {
+  # If multi module build and no MAVEN_BUILD_DIR is set --> error
+  if [ x"${MAVEN_BUILD_DIR}" = x ]; then
+    echo "${MAVEN_ARGS} ${MAVEN_EXTRA_ARGS}" | grep -q ' -pl'
+    if [ $? -eq 0 ]; then
+       echo "\$MAVEN_BUILD_DIR must be set for multi module Maven builds"
+       exit 1
+    fi
+  fi
+
   # Where artifacts are created within the build
   local dir=${MAVEN_BUILD_DIR:-${S2I_SOURCE_DIR}/target}
 
@@ -56,10 +63,10 @@ function copy_dir() {
 }
 
 function build_maven() {
-  # Where artefacts are created during build
-  local output_dir=$1
+  # Where artifacts are created during build
+  local build_dir=$1
 
-  # Where to put the artefacts
+  # Where to put the artifacts
   local app_dir=$2
 
   # Use main class if given
@@ -84,7 +91,7 @@ function build_maven() {
 
   # ==================================================================
   # Check for hawt-app dir and if not present run hawt-app explicitly
-  if [ ! -d "${output_dir}/hawt-app" ]; then
+  if [ ! -d "${build_dir}/hawt-app" ]; then
      if [ x"${JAVA_MAIN_CLASS}" = x ]; then
        echo "No JAVA_MAIN_CLASS specified and no hawt-app-maven-plugin configured in the pom.xml"
        exit 1
@@ -93,14 +100,17 @@ function build_maven() {
   fi
 
   # ==============
-  # Copy artefacts
-  echo "Copying Maven artifacts from ${output_dir}/hawt-app to ${app_dir} ..."
-  copy_dir "${output_dir}/hawt-app" ${app_dir}
+  # Copy artifacts
+  echo "Copying Maven artifacts from ${build_dir}/hawt-app to ${app_dir} ..."
+  copy_dir "${build_dir}/hawt-app" ${app_dir}
 
-  # cleanup maven build artifacts to reduce image size
+  # =============================
+  # cleanup maven build artifacts
   echo "Cleaning up maven build artifacts using mvn clean..."
   mvn ${maven_env_args} clean
 
+  # ======================
+  # Remove repo if desired
   if [ "x${MAVEN_CLEAR_REPO}" != "x" ]; then
     rm -rf "${S2I_ARTIFACTS_DIR}/m2"
     check_error "Cannot remove local Maven repository ${S2I_ARTIFACTS_DIR}/m2" $?
@@ -119,7 +129,7 @@ check_error "Cannot get output dir: $build_dir" $?
 if [ -f "${S2I_SOURCE_DIR}/pom.xml" ]; then
   echo "Detected Maven build"
   # If a pom.xml is present use maven
-  build_maven $(build_dir) ${DEPLOYMENTS_DIR}
+  build_maven ${build_dir} ${DEPLOYMENTS_DIR}
 else
   # Assuming that the source already contains compiled artefacts
   echo "Copying binaries from ${output_dir} to ${S2I_ARTIFACTS_DIR} ..."
